name: Build static

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_static:
    runs-on: ubuntu-latest
    container:
      image: ocamlpro/ocaml:4.12-2021-08-29
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: apk add bubblewrap m4 bash

      - run: opam init -y

      - name: Create switch
        run: opam switch create . ocaml-system --deps --locked -y

      - name: Install deps
        run: opam install . -y --deps-only

      - name: Build
        run: opam exec -- dune build --profile=release

      - name: Install
        run: opam exec -- dune install --profile=release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-4.12.0-static-hello
          path: _build/install/default/bin/hello

  silly_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mooreryan/lala_test_image@sha256:9809ec2536da1bd6fca3a22e9db1ca8b19fb3cad9e17e9fa1d4fda673ab8da60
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      # options: --user runner

    steps:
      - run: sudo apk add bubblewrap

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use OCaml 4.12.0
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
          dune-cache: true
          cache-prefix: v1-4.12.0

      - name: Install deps
        run: opam install . --deps-only --with-doc --with-test

      - name: Build
        run: opam exec -- dune build --profile=release

      - name: Install
        run: opam exec -- dune install --profile=release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-4.12.0-static-hello-2
          path: _build/install/default/bin/hello

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2
    #     with:
    #       path: apple_pie
    #       submodules: recursive

    #   - run: sudo apk add bubblewrap m4 bash

    #   - run: echo $GITHUB_WORKSPACE
    #   - run: ls $GITHUB_WORKSPACE
    #   - run: echo $HOME
    #   - run: ls $HOME
    #   - run: pwd
    #   - run: ls -lah
    #   # - run: ls -lah apple_pie
    #   - run: whoami

    #   # - run: sudo mkdir apple_pie

    #   - run: sudo opam init -y

    #   - name: Create switch
    #     run: sudo opam switch create . ocaml-system --deps --locked -y
    #     working-directory: apple_pie

    #   - name: Install deps
    #     run: sudo opam install . -y --deps-only
    #     working-directory: apple_pie

    #   - name: Build
    #     run: sudo opam exec -- dune build --profile=release
    #     working-directory: apple_pie

    #   - name: Install
    #     run: sudo opam exec -- dune install --profile=release
    #     working-directory: apple_pie

    #   - run: ls $GITHUB_WORKSPACE
    #   - run: ls $GITHUB_WORKSPACE/apple_pie
    #   - run: ls $GITHUB_WORKSPACE/apple_pie/_build
    #   - run: ls $GITHUB_WORKSPACE/apple_pie/_build/install
    #   - run: ls $GITHUB_WORKSPACE/apple_pie/_build/install/default
    #   - run: ls -lah $GITHUB_WORKSPACE/apple_pie/_build/install/default/bin

    #   - name: Upload the build artifact
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: alpine-4.12.0-static-hello
    #       path: $GITHUB_WORKSPACE/apple_pie/_build/install/default/bin
