name: Build static

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_static:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:alpine-ocaml-4.12
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use OCaml 4.12.0
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
          dune-cache: true
          cache-prefix: build-static

      - name: Build
        run: opam exec -- dune build --profile=release

      - name: Install
        run: opam exec -- dune install --profile=release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-4.12.0-static-pasv
          path: _build/install/default/hello
