name: Build static

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_static:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:alpine-ocaml-4.12
      options: --user 1001

    steps:
      - run: echo "SRC_ROOT=$HOME/gh_actions_ocaml_docker" >> $GITHUB_ENV

      - name: Checkout code
        run: git clone https://github.com/mooreryan/gh_actions_ocaml_docker.git "${SRC_ROOT}"

      - name: Build
        run: dune build
        working-directory: "${SRC_ROOT}"
