name: Build static

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_static:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:alpine-ocaml-4.12
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: eval $(opam env) && opam update -y
      - run: eval $(opam env) && opam install . -y --deps-only

      - name: Build
        run: eval $(opam env) && dune build --profile=release

      - name: Install
        run: eval $(opam env) && dune install --profile=release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-4.12.0-static-pasv
          path: _build/install/default/hello
